Add annotation in order to reload kafka-proxy sts
ricardo-ch/helm-charts pull request #52
Opened 2022-06-29 14:25 UTC by LouisPouliquen

2022-07-04 09:22 UTC, golonzovsky approved these changes

2022-07-04 09:23 UTC, bueti requested changes
can you make this configurable?

2022-07-04 14:54 UTC, bueti approved these changes
edit: wrong button 🤦

2022-07-04 14:54 UTC, bueti requested changes

2022-07-04 14:54 UTC, bueti commented on charts/kafka-proxy/values.yaml
> +  onChange: false
please add a comment `# -- <explanation>`. this will be picked up by helm-docs and automatically added to the readme.

2022-07-04 14:55 UTC, bueti commented on charts/kafka-proxy/values.yaml
> +  onChange: false
see https://github.com/ricardo-ch/helm-charts/runs/7182084608?check_suite_focus=true

2022-07-26 12:17 UTC, bueti approved these changes
lgtm, just make the build pass, then you can merge :)

2022-07-26 14:45 UTC, merged